### PR TITLE
Add support for Russian alphabet

### PR DESCRIPTION
**Pull request by mnaoumov**
I added the phonetic translation for the Russian alphabet as I want it to be included in your awesome website to help other people to spell Russian words over the phone.

### CODE REVIEW

**Comment by ffraenz** [comment]
Thank you for your pull request! Checking back on the [Russian spelling alphabet](https://en.wikipedia.org/wiki/Russian_spelling_alphabet) & [Фонетический алфавит](https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82) some words are not spelled like they are in the official version: 'Анна' instead of 'А́нна', 'Борис' instead of 'Бори́с' and 'Василий' instead of 'Васи́лий' to just name a few.

Is there a reasoning behind this? In general I'd like to make sure we stick close to the official or original version of a translation method. If this is a variant, it should be labeled as such.

**Comment by mnaoumov** [comment]
@ffraenz those accent marks are just word stress signs and they are completely optional.
Like in English you use **Bravo** instead of **Brávo**.

In order to support official versions, I will make a few more changes

**Comment by mnaoumov** [comment]
Fixes #63

**Comment by ffraenz** [comment]
Thank you for the clarification!

**Pull request merged**
