### PR TITLE
Extract alphabets configuration into a separate file

### LINKED ISSUE #81: Library feature: Brick resource dependencies
**Describe your feature or enhancement suggestion**

There are bricks that need a lot of knowledge or data to operate. To keep the code base small and efficient we therefore need to separate the knowledge from the logic into separate / external resources that are only loaded when the brick is being used. This may also be the first step towards implementing Web Assembly logic in this project as WASM files are external resources, too.

Open questions:
- [ ] Where to put / host the resources and how to organise them?
- [ ] How to load resources in a Node.js environment (e.g. for unit tests or library dependents)?
- [ ] How to make resources available in the local development environment? Is a web server (e.g. Docker) necessary to deliver the resources?

**Describe a concrete use case**

- Offering a more complete set of languages & variants in the Spelling Alphabet brick (#66, #76, #78)
- Reduce the size of the Enigma encoder by outsourcing model and rotor data.

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #81 

In order to keep future merging simpler, I based the code on the #78 that are not merged yet but it is not required and can be easily rebased.

The biggest chunk of this PR is to make an ability to construct bricks asynchronously. Bunch of API methods were changed to `async`

This was required as loading configuration from an external file is an asynchronous operation by its nature

In order to support loading resources from both Node.JS and browser, I detect the environment and use `fs` or `fetch` accordingly

### CODE REVIEW

**Comment by mnaoumov** [comment]
Hmm... locally tests are passing...

**Comment by mnaoumov** [comment]
Got it! I just had to merge the latest changes

**Comment by mnaoumov** [comment]
@ffraenz do you mind me asking why my pull request is not merged? I think even if you are not happy with the implementation, it can be easily refactored afterward.

**Comment by ffraenz** [comment]
@mnaoumov Sorry for the lack of feedback about your contributions. You are proposing profound structural changes to the project which do take time to consider. In addition my studies require a lot of attention at the moment.

I am currently working on a prototype for the next major version to test a different strategy. I'd like to use Webpack to introduce code splitting and dynamic importing of bricks and their dependencies. This may allow us to (1) load the brick's source in the browser only when it's actually added to the pipe and to (2) move bricks with their dependencies into own repositories. At this point the resources needed by a brick won't matter neither to the page load stats nor to the repository size. It would even be possible to allow third party bricks from foreign repositories to be run on the platform.

I am currently awaiting feedback on a related [Stackoverflow question](https://stackoverflow.com/questions/58901229). Once a final strategy is found for the next major version (which may also introduce breaking changes to the structure) I will definitely consider your proposals.

**Comment by mnaoumov** [comment]
@ffraenz thanks for your reply. But I think what you are trying to address with Webpack is slightly unrelated to the changes I've suggested. Essentially the idea is to add `initAsync` methods to cover a lack of async constructors in JavaScript. Having that implemented will allow you to delay bricks construction until they are fully ready to be constructed. I think this approach would be useful even if you switch to your Webpack approach

**Pull request closed without merging**
