### PR TITLE
Localize spaces

### PR DESCRIPTION
**Pull request by mnaoumov**
Added translated version of (space) token to get more native spelling experience

### CODE REVIEW

**Comment by ffraenz** [comment]
Thank you again, for your pull requests. As German nouns are capitalized, please also capitalize the space word `(Leertaste)`. After that your PR is ready to be merged.

**Comment by mnaoumov** [comment]
@ffraenz fixed

**Comment by mnaoumov** [comment]
Fixes #64

**Comment by mnaoumov** [comment]
Apparently, I failed trying to create independent pull requests. All of the stacks up. So this one does not make sense individually. Closing it. Proceed with #61

**Pull request closed without merging**
